# Kunskapskontroll 1 

## 1. Inledning och kontext

Detta dataset representerar en simulering och statististisk sammaställning av de 48 landslag som förväntas delta i **FIFA World Cup 2026**

**Om datan:**
- **Källor:** Det används två filer från kaggle: fifa_history.csv ( historisk statistik från tidigare vm) samt fifa_2026.csv (statisitk simulering av de 48 lagen inför vm 2026)
- **Population:** Varje rad representerar ett specifikt landslag. 
- **Variabler:** Datasetet innehåller 24 kolumner med allt från historiska meriter (tidigare titlar) till nuvarande form (mål och vinster de senaste 4 åren)
- **Syfte:** Att undersöka faktorer som påverkar ett lags förväntade framgång inför det utökade VM-formatet
- **Begränsningar:*Eftersom jag slår ihop två dataset där vi har historisk data och framtida data. Detta gör att viss data kommer inte att finnas till exempel på winner för 2026. jag väljer att radera dessa tomma rader automatiskt. Detta för att inte medvetet blanda ihop faktiska resultat med framtidsprogrnoser utifrån missvisande sätt.

In [1]:
# importera de olika paketen. Vi använder oss av matplotlib och seabord för att skapa visuella diagram 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### hämta in dataseten som jag ska arbeta med och se hur stora de är

In [7]:
# Ladda in båda dataseten
df_history = pd.read_csv("data/fifa_history.csv")
df_2026 = pd.read_csv("data/fifa_2026.csv")

# Inspektera storleken på båda


# En snabb titt på de första raderna i historiken
print("history table")
print(f"Historik (Train): {df_history.shape[0]} rader, {df_history.shape[1]} kolumner")
display(df_history.head(3))

print(" ")
print("wc 2026 table")
print(f"VM 2026 (Test): {df_2026.shape[0]} rader, {df_2026.shape[1]} kolumner")
display(df_2026.head(3))

history table
Historik (Train): 192 rader, 24 kolumner

,version,team,continent,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,...,world_cup_participations_before,groups_passed_before,round16_before,quarterfinals_before,semifinals_before,finals_before,winner,finalist,semi_finalist,quarter_finalist
0,2006,Angola,Africa,0,61,49,19,13,14,0,...,0,0,0,0,0,0,0,0,0,0
1,2006,Argentina,South America,0,97,55,31,10,10,2,...,13,10,5,6,4,4,0,0,0,1
2,2006,Australia,Oceania,0,101,34,23,8,5,0,...,1,0,0,0,0,0,0,0,0,0

wc 2026 table
VM 2026 (Test): 48 rader, 24 kolumner

,version,team,continent,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,...,world_cup_participations_before,groups_passed_before,round16_before,quarterfinals_before,semifinals_before,finals_before,winner,finalist,semi_finalist,quarter_finalist
0,2026,France,Europe,0,85,32,25,6,7,2,...,16,10,8,9,7,4,NaN,NaN,NaN,NaN
1,2026,Spain,Europe,0,104,32,29,2,8,1,...,16,11,9,6,2,1,NaN,NaN,NaN,NaN
2,2026,Argentina,South America,0,80,14,30,4,3,3,...,18,15,10,10,6,6,NaN,NaN,NaN,NaN

### Sammanslagningen
här slår vi ihopa de två dataseten till en.

In [8]:
# 1. (Valfritt men smart) Ge dem en "etikett" så vi vet vad som är vad sen
df_history["status"] = "Historik"
df_2026["status"] = "2026"

# 2. Slå ihop dem (Concatenate)
# ignore_index=True gör att vi får en ny snygg numrering från 0 till slutet
df = pd.concat([df_history, df_2026], ignore_index=True)

# 3. Kontrollera resultatet
print(f"Nu är de ett! Totalt antal rader: {df.shape[0]}")
display(df.tail())  # Kolla på slutet av listan, där bör 2026-datan ligga nu

Nu är de ett! Totalt antal rader: 240

,version,team,continent,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,...,groups_passed_before,round16_before,quarterfinals_before,semifinals_before,finals_before,winner,finalist,semi_finalist,quarter_finalist,status
235,2026,Cape Verde,Africa,0,46,39,16,10,12,0,...,0,0,0,0,0,NaN,NaN,NaN,NaN,2026
236,2026,Ghana,Africa,0,46,42,12,13,9,0,...,2,2,1,0,0,NaN,NaN,NaN,NaN,2026
237,2026,Cura?o,North America,0,55,39,12,10,10,0,...,0,0,0,0,0,NaN,NaN,NaN,NaN,2026
238,2026,Haiti,North America,0,71,37,16,8,8,0,...,0,0,0,0,0,NaN,NaN,NaN,NaN,2026
239,2026,New Zealand,Oceania,0,63,32,13,12,6,0,...,0,0,0,0,0,NaN,NaN,NaN,NaN,2026

In [ ]:
## 3. Datatvätt